executed with `ControlledError("exit code 1")`
